include:
  - project: chromaway/core-infra/gitlab-automation
    ref: 1.1.6
    file:
      - templates/release.yml
      - templates/container-dependency-scanning.yml

image: registry.gitlab.com/chromaway/core-tools/chromia-images/node22-java21:1.0.0@sha256:aa1ae82142ad06190f9c2b3373887dfdecb929a005a7f7bf939f1667d85b7ff3

stages:
  - build
  - release
  - deploy

variables:
  GRADLE_USER_HOME: "$CI_PROJECT_DIR/.gradle"

build:
  stage: build
  before_script:
    - apk add --no-cache openjdk21
    - export GRADLE_USER_HOME
  script:
    - ./gradlew check --info
    - npm install -g jdeploy
    - npm run build
    - jdeploy install
  artifacts:
    paths:
      - "jdeploy-bundle/"
      - "app/build/libs/"
    expire_in: 1 week
  cache:
    key: "$CI_COMMIT_REF_NAME"
    policy: pull-push
    paths:
      - "**/build"
      - ".gradle"

deploy-npm:
  stage: deploy
  variables:
    NPM_TOKEN: $NPM_TOKEN
  before_script:
    - apk add --no-cache openjdk21
    - npm config set //registry.npmjs.org/:_authToken $NPM_TOKEN
    - npm whoami
    - export GRADLE_USER_HOME
  script:
    - npm publish --dry-run --tag $CI_COMMIT_TAG
  rules:
    - if: '$CI_COMMIT_BRANCH == "dev"'
    - if: $CI_COMMIT_TAG =~ /^[0-9]+\.[0-9]+\.[0-9]+$/
  dependencies:
    - build

deploy-image:
  stage: deploy
  before_script:
    - apk add --no-cache openjdk21
    - export GRADLE_USER_HOME
  script:
    - ./gradlew jib
  rules:
    - if: '$CI_COMMIT_BRANCH == "dev"'
      when: manual
  dependencies:
    - build

release-patch:
  extends: .release
  stage: release
  script:
    - |
      NEXT_VERSION="$MAJOR.$MINOR.$((PATCH + 1))"
      echo "Current version is $CURRENT_VERSION"
      echo "Will create new version $NEXT_VERSION"

      echo "Checking if version $NEXT_VERSION is documented in changelog..."
      git tag $MAJOR.$MINOR.$((PATCH + 1))
      git push --tags
  only:
    - dev
    - /^support\/.*$/

release-minor:
  extends: .release
  stage: release
  script:
    - |
      NEXT_VERSION="$MAJOR.$((MINOR + 1)).0"
      echo "Current version is $CURRENT_VERSION"
      echo "Will create new version $NEXT_VERSION"
      git tag $MAJOR.$((MINOR + 1)).0
      git push --tags
  only:
    - dev
    - /^support\/.*$/
