<?xml version="1.0" encoding="UTF-8"?>
<project xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xmlns="http://maven.apache.org/POM/4.0.0"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <parent>
        <groupId>com.chromia.cli</groupId>
        <artifactId>chromia-cli-parent</artifactId>
        <version>${revision}</version>
    </parent>

    <artifactId>chromia-cli</artifactId>
    <version>${revision}</version>
    <packaging>jar</packaging>

    <name>Chromia Cli</name>

    <properties>
        <revision>dev</revision>
        <directory.source>${project.parent.build.directory}/directory-chain/src</directory.source>
        <library-chain.source>${project.parent.build.directory}/library-chain/src</library-chain.source>
        <directory.config>${directory.source}/../chromia.yml</directory.config>
        <library-chain.config>${library-chain.source}/../chromia.yml</library-chain.config>

        <assembly.path>${project.basedir}/src/main/assembly/targz.xml</assembly.path>

        <image.name>chr</image.name>
        <main.class>com.chromia.MainKt</main.class>
    </properties>


    <build>
        <plugins>
            <plugin>
                <groupId>org.jetbrains.kotlin</groupId>
                <artifactId>kotlin-maven-plugin</artifactId>
            </plugin>
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-jar-plugin</artifactId>
            </plugin>
            <plugin>
                <groupId>net.postchain.rell</groupId>
                <artifactId>rell-maven-plugin</artifactId>
                <configuration>
                    <packageName/>
                    <testModule/>
                    <postchainClientConfig>
                        <failover.attempts>2</failover.attempts>
                        <connect.timeout>10000</connect.timeout>
                    </postchainClientConfig>
                </configuration>
                <executions>
                    <execution>
                        <id>rell-client-gen</id>
                        <phase>generate-resources</phase>
                        <goals>
                            <goal>rell-install</goal>
                            <goal>rell-generate-client</goal>
                        </goals>
                        <configuration>
                            <source>${directory.source}</source>
                            <packageName>com.chromia.directory1</packageName>
                            <mainModule>
                                common.queries,proposal_voter_set,proposal_blockchain,proposal_container
                            </mainModule>
                            <configFile>${directory.config}</configFile>
<!--                            <target>${project.build.directory}/generated-sources/rell-client-directory</target>-->
                        </configuration>
                    </execution>
                    <execution>
                        <id>library-chain-client-gen</id>
                        <phase>generate-resources</phase>
                        <goals>
                            <goal>rell-install</goal>
                            <goal>rell-generate-client</goal>
                        </goals>
                        <configuration>
                            <source>${library-chain.source}</source>
                            <packageName>com.chromia.library.chain</packageName>
                            <mainModule>main</mainModule>
                            <configFile>${library-chain.config}</configFile>
                            <target>${project.build.directory}/generated-sources/rell-client-library</target>
                        </configuration>
                    </execution>
                </executions>
            </plugin>
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-assembly-plugin</artifactId>
                <executions>
                    <execution>
                        <id>make-archive</id>
                        <phase>package</phase>
                        <goals>
                            <goal>single</goal>
                        </goals>
                        <configuration>
                            <descriptors>
                                <descriptor>${assembly.path}</descriptor>
                            </descriptors>
                        </configuration>
                    </execution>
                </executions>
            </plugin>
            <plugin>
                <groupId>org.codehaus.mojo</groupId>
                <artifactId>exec-maven-plugin</artifactId>
                <version>1.6.0</version>
                <configuration>
                    <mainClass>${main.class}</mainClass>
                </configuration>
            </plugin>
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-compiler-plugin</artifactId>
            </plugin>

            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-surefire-plugin</artifactId>
            </plugin>
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-failsafe-plugin</artifactId>
            </plugin>

            <plugin>
                <groupId>pl.project13.maven</groupId>
                <artifactId>git-commit-id-plugin</artifactId>
            </plugin>

        </plugins>

        <pluginManagement>
            <plugins>
                <plugin>
                    <groupId>com.google.cloud.tools</groupId>
                    <artifactId>jib-maven-plugin</artifactId>
                    <configuration>
                        <allowInsecureRegistries>false</allowInsecureRegistries>
                        <from>
                            <image>
                                registry.gitlab.com/chromaway/core-tools/chromia-images/java21:1.0.17@sha256:6b4f6b890ece55335f98b675318ffdcddc23878eaf80999a2e0844b8f0f305e6
                            </image>
                        </from>
                        <to>
                            <image>${image.name}</image>
                        </to>
                        <container>
                            <entrypoint>
                                <args>/usr/bin/chr-entrypoint.sh</args>
                            </entrypoint>
                            <args>
                                <arg>chr</arg>
                            </args>
                            <appRoot>/usr/share/chr</appRoot>
                            <workingDirectory>/usr/app</workingDirectory>
                            <mainClass>${main.class}</mainClass>
                            <creationTime>${git.commit.time}</creationTime>
                            <filesModificationTime>${git.commit.time}</filesModificationTime>
                        </container>
                        <extraDirectories>
                            <permissions>
                                <permission>
                                    <file>/usr/bin/chr</file>
                                    <mode>755</mode>
                                </permission>
                                <permission>
                                    <file>/usr/bin/chr-entrypoint.sh</file>
                                    <mode>755</mode>
                                </permission>
                            </permissions>
                        </extraDirectories>
                        <containerizingMode>packaged</containerizingMode>
                    </configuration>
                    <executions>
                        <execution>
                            <id>docker-tar</id>
                            <phase>package</phase>
                            <goals>
                                <goal>buildTar</goal>
                            </goals>
                        </execution>
                        <execution>
                            <id>docker-build</id>
                            <phase>install</phase>
                            <goals>
                                <goal>dockerBuild</goal>
                            </goals>
                        </execution>
                    </executions>
                </plugin>
            </plugins>
        </pluginManagement>
    </build>

    <dependencies>

        <!--TODO: Remove this dependency after proposal has been re-factored*/ -->
        <dependency>
            <groupId>io.github.java-diff-utils</groupId>
            <artifactId>java-diff-utils</artifactId>
            <version>4.12</version>
        </dependency>

        <dependency>
            <groupId>com.chromia.cli.tools</groupId>
            <artifactId>chromia-build-tools</artifactId>
            <version>${chromia.cli.tools.version}</version>
        </dependency>
        <dependency>
            <groupId>com.chromia.cli.tools</groupId>
            <artifactId>chromia-build-tools</artifactId>
            <version>${chromia.cli.tools.version}</version>
            <type>test-jar</type>
            <scope>test</scope>
        </dependency>
        <dependency>
            <groupId>com.chromia.cli.tools</groupId>
            <artifactId>chromia-cli-tools</artifactId>
            <version>${chromia.cli.tools.version}</version>
        </dependency>
        <dependency>
            <groupId>net.postchain.rell</groupId>
            <artifactId>rell-api-gtx</artifactId>
        </dependency>
        <dependency>
            <groupId>net.postchain.rell</groupId>
            <artifactId>rell-api-shell</artifactId>
        </dependency>
        <dependency>
            <groupId>net.postchain.rell</groupId>
            <artifactId>rell-api-base</artifactId>
        </dependency>
        <dependency>
            <groupId>net.postchain.client</groupId>
            <artifactId>postchain-client</artifactId>
        </dependency>
        <dependency>
            <groupId>net.postchain.client</groupId>
            <artifactId>chromia-client</artifactId>
        </dependency>
        <dependency>
            <groupId>net.postchain.client</groupId>
            <artifactId>ft4-client</artifactId>
        </dependency>
        <dependency>
            <groupId>net.postchain</groupId>
            <artifactId>postchain-base</artifactId>
        </dependency>
        <dependency>
            <groupId>net.postchain</groupId>
            <artifactId>postchain-gtv</artifactId>
        </dependency>
        <dependency>
            <groupId>net.postchain</groupId>
            <artifactId>postchain-gtv-yaml</artifactId>
            <version>${postchain.version}</version>
        </dependency>
        <dependency>
            <groupId>net.postchain</groupId>
            <artifactId>postchain-gtx-data</artifactId>
        </dependency>
        <dependency>
            <groupId>net.postchain</groupId>
            <artifactId>chromia-infrastructure</artifactId>
            <scope>runtime</scope>
        </dependency>
        <dependency>
            <groupId>net.postchain.rell</groupId>
            <artifactId>rell-codegen-kotlin</artifactId>
        </dependency>
        <dependency>
            <groupId>net.postchain.rell</groupId>
            <artifactId>rell-codegen-typescript</artifactId>
        </dependency>
        <dependency>
            <groupId>net.postchain.rell</groupId>
            <artifactId>rell-codegen-mermaid</artifactId>
        </dependency>
        <dependency>
            <groupId>net.postchain.rell</groupId>
            <artifactId>rell-codegen-javascript</artifactId>
        </dependency>
        <dependency>
            <groupId>net.postchain.rell</groupId>
            <artifactId>rell-codegen-python</artifactId>
        </dependency>
        <dependency>
            <groupId>net.postchain.rell</groupId>
            <artifactId>rell-codegen</artifactId>
        </dependency>
        <dependency>
            <groupId>net.postchain</groupId>
            <artifactId>postchain-eif-core</artifactId>
            <version>${eif.version}</version>
        </dependency>
        <dependency>
            <groupId>net.postchain.rell</groupId>
            <artifactId>rell-dokka-plugin</artifactId>
            <version>${rell.version}</version>
        </dependency>
        <dependency>
            <groupId>net.postchain.rell</groupId>
            <artifactId>rell-toolbox-code-quality</artifactId>
        </dependency>
        <dependency>
            <groupId>net.postchain.rell</groupId>
            <artifactId>rell-toolbox-seeder</artifactId>
        </dependency>
        <dependency>
            <groupId>net.postchain.rell</groupId>
            <artifactId>rell-toolbox-indexer</artifactId>
            <exclusions>
                <exclusion>
                    <groupId>com.chromia.cli</groupId>
                    <artifactId>chromia-build-tools</artifactId>
                </exclusion>
            </exclusions>
        </dependency>
        <dependency>
            <groupId>net.postchain.rell</groupId>
            <artifactId>rell-toolbox-common</artifactId>
            <exclusions>
                <exclusion>
                    <groupId>com.chromia.cli</groupId>
                    <artifactId>chromia-build-tools</artifactId>
                </exclusion>
            </exclusions>
        </dependency>

        <dependency>
            <groupId>com.github.ajalt.clikt</groupId>
            <artifactId>clikt-jvm</artifactId>
        </dependency>
        <dependency>
            <groupId>com.github.ajalt.clikt</groupId>
            <artifactId>clikt-markdown-jvm</artifactId>
        </dependency>
        <dependency>
            <groupId>com.github.ajalt.mordant</groupId>
            <artifactId>mordant-jvm-jna-jvm</artifactId>
        </dependency>
        <dependency>
            <groupId>com.github.ajalt.mordant</groupId>
            <artifactId>mordant-coroutines</artifactId>
        </dependency>
        <dependency>
            <groupId>com.github.ajalt.mordant</groupId>
            <artifactId>mordant-coroutines-jvm</artifactId>
        </dependency>
        <dependency>
            <groupId>org.apache.commons</groupId>
            <artifactId>commons-text</artifactId>
        </dependency>

        <dependency>
            <groupId>com.fasterxml.jackson.dataformat</groupId>
            <artifactId>jackson-dataformat-yaml</artifactId>
            <scope>runtime</scope>
        </dependency>

        <dependency>
            <groupId>org.apache.logging.log4j</groupId>
            <artifactId>log4j-slf4j-impl</artifactId>
            <scope>runtime</scope>
        </dependency>
        <dependency>
            <groupId>dev.forkhandles</groupId>
            <artifactId>result4k</artifactId>
        </dependency>
        <dependency>
            <groupId>org.http4k</groupId>
            <artifactId>http4k-core</artifactId>
        </dependency>
        <dependency>
            <groupId>org.http4k</groupId>
            <artifactId>http4k-server-netty</artifactId>
        </dependency>
        <dependency>
            <groupId>org.http4k</groupId>
            <artifactId>http4k-format-jackson</artifactId>
        </dependency>

        <dependency>
            <groupId>org.junit.jupiter</groupId>
            <artifactId>junit-jupiter</artifactId>
            <scope>test</scope>
        </dependency>
        <dependency>
            <groupId>io.mockk</groupId>
            <artifactId>mockk-jvm</artifactId>
            <version>1.13.13</version>
            <scope>test</scope>
        </dependency>
        <dependency>
            <groupId>net.postchain</groupId>
            <artifactId>postchain-devtools</artifactId>
            <scope>test</scope>
        </dependency>
        <dependency>
            <groupId>uk.org.webcompere</groupId>
            <artifactId>system-stubs-jupiter</artifactId>
            <scope>test</scope>
        </dependency>
        <dependency>
            <groupId>org.apache.logging.log4j</groupId>
            <artifactId>log4j-core-test</artifactId>
            <scope>test</scope>
        </dependency>
        <dependency>
            <groupId>org.redundent</groupId>
            <artifactId>kotlin-xml-builder</artifactId>
            <scope>test</scope>
        </dependency>
    </dependencies>

    <profiles>
        <profile>
            <id>docker</id>
            <build>
                <plugins>
                    <plugin>
                        <groupId>com.google.cloud.tools</groupId>
                        <artifactId>jib-maven-plugin</artifactId>
                    </plugin>
                </plugins>
            </build>
        </profile>
        <profile>
            <id>docker-arm</id>
            <activation>
                <os>
                    <family>mac</family>
                    <arch>aarch64</arch>
                </os>
            </activation>
            <build>
                <pluginManagement>
                    <plugins>
                        <plugin>
                            <groupId>com.google.cloud.tools</groupId>
                            <artifactId>jib-maven-plugin</artifactId>
                            <executions>
                                <execution>
                                    <id>docker-build</id>
                                    <configuration>
                                        <from>
                                            <platforms>
                                                <platform>
                                                    <os>linux</os>
                                                    <architecture>arm64</architecture>
                                                </platform>
                                            </platforms>
                                        </from>
                                    </configuration>
                                </execution>
                            </executions>
                        </plugin>
                    </plugins>
                </pluginManagement>
            </build>
        </profile>
        <profile>
            <id>docker-push</id>
            <build>
                <pluginManagement>
                    <plugins>
                        <plugin>
                            <groupId>com.google.cloud.tools</groupId>
                            <artifactId>jib-maven-plugin</artifactId>
                            <executions>
                                <execution>
                                    <id>docker-push</id>
                                    <phase>deploy</phase>
                                    <goals>
                                        <goal>build</goal>
                                    </goals>
                                    <configuration>
                                        <from>
                                            <platforms>
                                                <platform>
                                                    <architecture>amd64</architecture>
                                                    <os>linux</os>
                                                </platform>
                                                <platform>
                                                    <architecture>arm64</architecture>
                                                    <os>linux</os>
                                                </platform>
                                            </platforms>
                                        </from>
                                        <to>
                                            <image>${gitlab.registry}/${image.name}:${project.version}</image>
                                            <auth>
                                                <!--suppress UnresolvedMavenProperty -->
                                                <username>${env.CI_REGISTRY_USER}</username>
                                                <!--suppress UnresolvedMavenProperty -->
                                                <password>${env.CI_REGISTRY_PASSWORD}</password>
                                            </auth>
                                        </to>
                                    </configuration>
                                </execution>
                            </executions>
                        </plugin>
                    </plugins>
                </pluginManagement>
            </build>
        </profile>
    </profiles>

</project>
