<?xml version="1.0" encoding="UTF-8"?>
<project xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xmlns="http://maven.apache.org/POM/4.0.0"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <parent>
        <groupId>com.chromia</groupId>
        <artifactId>chromia-parent</artifactId>
        <version>0.2.5</version>
    </parent>

    <artifactId>chromia-cli-parent</artifactId>
    <groupId>com.chromia.cli</groupId>
    <version>${revision}</version>
    <packaging>pom</packaging>
    <modules>
        <module>chromia-cli</module>
        <module>coverage-report-aggregate</module>
    </modules>

    <name>Chromia Cli Parent</name>
    <properties>
        <revision>dev</revision>
        <postchain.version>3.49.16</postchain.version>
        <postchain-chromia.version>3.39.11</postchain-chromia.version>
        <postchain.client.version>3.39.5</postchain.client.version>
        <rell.version>0.16.6</rell.version>
        <eif.version>0.32.6</eif.version>
        <directory.chain.version>1.110.2</directory.chain.version>
        <chromia.cli.tools.version>0.12.4</chromia.cli.tools.version>
        <directory.source>${project.build.directory}/directory-chain/src</directory.source>
        <directory.config>${project.build.directory}/directory-chain/chromia.yml</directory.config>

        <jgit.version>6.9.0.202403050737-r</jgit.version>

        <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
        <kotlin.version>2.3.0</kotlin.version>
        <kotlin.compiler.jvmTarget>21</kotlin.compiler.jvmTarget>
        <kotlin.compiler.incremental>true</kotlin.compiler.incremental>
        <maven.compiler.source>21</maven.compiler.source>
        <maven.compiler.target>21</maven.compiler.target>
        <kotlin.code.style>obsolete</kotlin.code.style>

        <assembly.path>${project.basedir}/src/main/assembly/targz.xml</assembly.path>
        <image.platforms>linux/amd64,linux/arm64</image.platforms>
        <gitlab.registry>registry.gitlab.com/chromaway/core-tools/chromia-cli</gitlab.registry>
    </properties>

    <repositories>
        <repository>
            <id>chromia-parent</id>
            <name>Chromia parent GitLab Registry</name>
            <url>https://gitlab.com/api/v4/projects/50818999/packages/maven</url>
        </repository>
        <repository>
            <id>postchain-chromia</id>
            <url>https://gitlab.com/api/v4/projects/33481005/packages/maven</url>
        </repository>
        <repository>
            <id>postchain</id>
            <name>Postchain GitLab Registry</name>
            <url>https://gitlab.com/api/v4/projects/32294340/packages/maven</url>
        </repository>
        <repository>
            <id>postchain-client</id>
            <name>Postchain Client GitLab Registry</name>
            <url>https://gitlab.com/api/v4/projects/46288950/packages/maven</url>
        </repository>
        <repository>
            <id>rellr</id>
            <name>Rell Runtime Registry</name>
            <url>https://gitlab.com/api/v4/projects/32802097/packages/maven</url>
        </repository>
        <repository>
            <id>postchain-eif</id>
            <name>Postchain EIF Gtx module Registry</name>
            <url>https://gitlab.com/api/v4/projects/36768178/packages/maven</url>
        </repository>
        <repository>
            <id>chromia-cli-tools</id>
            <name>Chromia CLI Tools Registry</name>
            <url>https://gitlab.com/api/v4/projects/64941451/packages/maven</url>
        </repository>
        <repository>
            <id>mavenCentral</id>
            <url>https://repo1.maven.org/maven2/</url>
        </repository>
    </repositories>
    <pluginRepositories>
        <pluginRepository>
            <id>rell-maven</id>
            <url>https://gitlab.com/api/v4/projects/37668820/packages/maven</url>
        </pluginRepository>
    </pluginRepositories>
    <distributionManagement>
        <repository>
            <id>gitlab-maven</id>
            <url>https://gitlab.com/api/v4/projects/39844192/packages/maven</url>
        </repository>
    </distributionManagement>

    <build>
        <sourceDirectory>src/main/kotlin</sourceDirectory>
        <pluginManagement>
            <plugins>
                <plugin>
                    <groupId>net.postchain.rell</groupId>
                    <artifactId>rell-maven-plugin</artifactId>
                    <version>1.2.1</version>
                </plugin>
                <plugin>
                    <groupId>org.apache.maven.plugins</groupId>
                    <artifactId>maven-assembly-plugin</artifactId>
                    <version>3.2.0</version>
                </plugin>
                <plugin>
                    <groupId>org.jetbrains.kotlin</groupId>
                    <artifactId>kotlin-maven-plugin</artifactId>
                    <version>${kotlin.version}</version>
                    <executions>
                        <execution>
                            <id>compile</id>
                            <phase>compile</phase>
                            <goals>
                                <goal>compile</goal>
                            </goals>
                            <configuration>
                                <sourceDirs>
                                    <sourceDir>${project.basedir}/src/main/kotlin</sourceDir>
                                </sourceDirs>
                            </configuration>
                        </execution>
                        <execution>
                            <id>test-compile</id>
                            <phase>test-compile</phase>
                            <goals>
                                <goal>test-compile</goal>
                            </goals>
                            <configuration>
                                <sourceDirs>
                                    <sourceDir>${project.basedir}/src/test/kotlin</sourceDir>
                                </sourceDirs>
                            </configuration>
                        </execution>
                    </executions>
                </plugin>
                <plugin>
                    <groupId>org.apache.maven.plugins</groupId>
                    <artifactId>maven-surefire-plugin</artifactId>
                    <configuration>
                        <workingDirectory>${project.build.directory}/test</workingDirectory>
                    </configuration>
                </plugin>
                <plugin>
                    <groupId>org.apache.maven.plugins</groupId>
                    <artifactId>maven-failsafe-plugin</artifactId>
                    <configuration>
                        <environmentVariables>
                            <DIST_EXECUTABLE>
                                ${project.build.directory}/${project.artifactId}-${project.version}-dist/bin/chr
                            </DIST_EXECUTABLE>
                            <!--suppress UnresolvedMavenProperty -->
                            <JAVA_ARGS>${argLine}</JAVA_ARGS>
                            <PROJECT_VERSION>${project.version}</PROJECT_VERSION>
                        </environmentVariables>
                    </configuration>
                    <executions>
                        <execution>
                            <goals>
                                <goal>integration-test</goal>
                                <goal>verify</goal>
                            </goals>
                        </execution>
                    </executions>
                </plugin>
                <plugin>
                    <groupId>pl.project13.maven</groupId>
                    <artifactId>git-commit-id-plugin</artifactId>
                    <executions>
                        <execution>
                            <id>get-the-git-infos</id>
                            <goals>
                                <goal>revision</goal>
                            </goals>
                            <phase>initialize</phase>
                        </execution>
                    </executions>
                    <configuration>
                        <useNativeGit>true</useNativeGit> <!-- git worktree does not work with JGit implementation -->
                        <includeOnlyProperties>
                            <includeOnlyProperty>^git\.commit\.time$</includeOnlyProperty>
                        </includeOnlyProperties>
                        <dateFormatTimeZone>UTC</dateFormatTimeZone>
                        <dateFormat>yyyy-MM-dd'T'HH:mm:ssX</dateFormat>
                    </configuration>
                </plugin>
                <plugin>
                    <groupId>com.google.cloud.tools</groupId>
                    <artifactId>jib-maven-plugin</artifactId>
                    <version>3.3.2</version>
                </plugin>
                <plugin>
                    <groupId>org.owasp</groupId>
                    <artifactId>dependency-check-maven</artifactId>
                    <version>12.1.5</version>
                    <configuration>
                        <prettyPrint>true</prettyPrint>
                        <failBuildOnAnyVulnerability>true</failBuildOnAnyVulnerability>
                        <assemblyAnalyzerEnabled>false</assemblyAnalyzerEnabled>
                        <yarnAuditAnalyzerEnabled>false</yarnAuditAnalyzerEnabled>
                        <suppressionFiles>
                            <suppressionFile>
                                https://gitlab.com/chromaway/chromia-parent/-/raw/dev/common-dependencies-suppression.xml?ref_type=heads
                            </suppressionFile>
                            <suppressionFile>dependencies-suppression.xml</suppressionFile>
                        </suppressionFiles>
                    </configuration>
                </plugin>
            </plugins>
        </pluginManagement>
    </build>

    <dependencyManagement>
        <dependencies>
            <dependency>
                <groupId>org.jetbrains.kotlin</groupId>
                <artifactId>kotlin-bom</artifactId>
                <version>${kotlin.version}</version>
                <scope>import</scope>
                <type>pom</type>
            </dependency>
            <dependency>
                <groupId>net.postchain</groupId>
                <artifactId>postchain</artifactId>
                <version>${postchain.version}</version>
                <type>pom</type>
                <scope>import</scope>
            </dependency>
            <dependency>
                <groupId>net.postchain</groupId>
                <artifactId>postchain-chromia</artifactId>
                <version>${postchain-chromia.version}</version>
                <type>pom</type>
                <scope>import</scope>
            </dependency>
            <dependency>
                <groupId>org.junit</groupId>
                <artifactId>junit-bom</artifactId>
                <version>5.9.1</version>
                <type>pom</type>
                <scope>import</scope>
            </dependency>
            <dependency>
                <groupId>com.chromia.cli</groupId>
                <artifactId>chromia-cli</artifactId>
                <version>${project.version}</version>
            </dependency>
            <dependency>
                <groupId>com.chromia.cli.tools</groupId>
                <artifactId>chromia-cli-tools</artifactId>
                <version>${chromia.cli.tools.version}</version>
            </dependency>
            <dependency>
                <groupId>com.chromia.cli.tools</groupId>
                <artifactId>chromia-build-tools</artifactId>
                <version>${chromia.cli.tools.version}</version>
            </dependency>
            <dependency>
                <groupId>net.postchain.rell</groupId>
                <artifactId>rell-api-gtx</artifactId>
                <version>${rell.version}</version>
            </dependency>
            <dependency>
                <groupId>net.postchain.rell</groupId>
                <artifactId>rell-gtx</artifactId>
                <version>${rell.version}</version>
            </dependency>
            <dependency>
                <groupId>net.postchain.rell</groupId>
                <artifactId>rell-api-shell</artifactId>
                <version>${rell.version}</version>
            </dependency>
            <dependency>
                <groupId>net.postchain.rell</groupId>
                <artifactId>rell-api-base</artifactId>
                <version>${rell.version}</version>
            </dependency>
            <dependency>
                <groupId>net.postchain.client</groupId>
                <artifactId>postchain-client</artifactId>
                <version>${postchain.client.version}</version>
            </dependency>
            <dependency>
                <groupId>net.postchain.client</groupId>
                <artifactId>chromia-client</artifactId>
                <version>${postchain.client.version}</version>
            </dependency>
            <dependency>
                <groupId>net.postchain.client</groupId>
                <artifactId>ft4-client</artifactId>
                <version>${postchain.client.version}</version>
            </dependency>
            <dependency>
                <groupId>net.postchain</groupId>
                <artifactId>postchain-base</artifactId>
                <version>${postchain.version}</version>
                <exclusions>
                    <exclusion>
                        <groupId>net.postchain</groupId>
                        <artifactId>postchain-admin-service</artifactId>
                    </exclusion>
                    <exclusion>
                        <groupId>io.grpc</groupId>
                        <artifactId>grpc-api</artifactId>
                    </exclusion>
                </exclusions>
            </dependency>
            <dependency>
                <groupId>net.postchain.rell</groupId>
                <artifactId>rell-codegen-kotlin</artifactId>
                <version>${rell.version}</version>
            </dependency>
            <dependency>
                <groupId>net.postchain.rell</groupId>
                <artifactId>rell-codegen-mermaid</artifactId>
                <version>${rell.version}</version>
            </dependency>
            <dependency>
                <groupId>net.postchain.rell</groupId>
                <artifactId>rell-codegen-typescript</artifactId>
                <version>${rell.version}</version>
            </dependency>
            <dependency>
                <groupId>net.postchain.rell</groupId>
                <artifactId>rell-codegen-javascript</artifactId>
                <version>${rell.version}</version>
            </dependency>
            <dependency>
                <groupId>net.postchain.rell</groupId>
                <artifactId>rell-codegen-python</artifactId>
                <version>${rell.version}</version>
            </dependency>
            <dependency>
                <groupId>net.postchain.rell</groupId>
                <artifactId>rell-codegen</artifactId>
                <version>${rell.version}</version>
            </dependency>
            <dependency>
                <groupId>net.postchain.rell</groupId>
                <artifactId>rell-toolbox-code-quality</artifactId>
                <version>${rell.version}</version>
            </dependency>
            <dependency>
                <groupId>net.postchain.rell</groupId>
                <artifactId>rell-toolbox-seeder</artifactId>
                <version>${rell.version}</version>
            </dependency>
            <dependency>
                <groupId>net.postchain.rell</groupId>
                <artifactId>rell-toolbox-indexer</artifactId>
                <version>${rell.version}</version>
            </dependency>
            <dependency>
                <groupId>net.postchain.rell</groupId>
                <artifactId>rell-toolbox-common</artifactId>
                <version>${rell.version}</version>
            </dependency>
            <dependency>
                <groupId>org.eclipse.jgit</groupId>
                <artifactId>org.eclipse.jgit</artifactId>
                <version>${jgit.version}</version>
            </dependency>
            <dependency>
                <groupId>org.eclipse.jgit</groupId>
                <artifactId>org.eclipse.jgit.ssh.apache</artifactId>
                <version>${jgit.version}</version>
            </dependency>
            <dependency>
                <groupId>org.eclipse.jgit</groupId>
                <artifactId>org.eclipse.jgit.ssh.apache.agent</artifactId>
                <version>${jgit.version}</version>
            </dependency>
            <dependency>
                <groupId>org.jetbrains.kotlinx</groupId>
                <artifactId>kotlinx-coroutines-core-jvm</artifactId>
                <version>1.7.3</version>
            </dependency>
            <dependency>
                <groupId>org.jetbrains.kotlinx</groupId>
                <artifactId>kotlinx-coroutines-test</artifactId>
                <version>1.7.3</version>
                <scope>test</scope>
            </dependency>
            <dependency>
                <groupId>com.github.ajalt.clikt</groupId>
                <artifactId>clikt-jvm</artifactId>
                <version>5.1.0</version>
            </dependency>
            <dependency>
                <groupId>com.github.ajalt.clikt</groupId>
                <artifactId>clikt-markdown-jvm</artifactId>
                <version>5.1.0</version>
            </dependency>
            <dependency>
                <groupId>org.jetbrains</groupId>
                <artifactId>markdown-jvm</artifactId>
                <version>0.7.3</version>
            </dependency>
            <dependency>
                <groupId>com.github.ajalt.mordant</groupId>
                <artifactId>mordant-jvm-jna-jvm</artifactId>
                <version>3.0.2</version>
            </dependency>
            <dependency>
                <groupId>com.github.ajalt.mordant</groupId>
                <artifactId>mordant-coroutines-jvm</artifactId>
                <version>3.0.2</version>
            </dependency>
            <dependency>
                <groupId>com.github.ajalt.mordant</groupId>
                <artifactId>mordant-coroutines</artifactId>
                <version>3.0.2</version>
            </dependency>
            <dependency>
                <groupId>org.apache.logging.log4j</groupId>
                <artifactId>log4j-slf4j-impl</artifactId>
                <version>2.19.0</version>
                <scope>runtime</scope>
            </dependency>
            <dependency>
                <groupId>dev.forkhandles</groupId>
                <artifactId>result4k</artifactId>
                <version>2.4.0.0</version>
            </dependency>
            <dependency>
                <groupId>org.http4k</groupId>
                <artifactId>http4k-format-jackson</artifactId>
                <version>4.34.0.4</version>
            </dependency>
            <dependency>
                <groupId>org.redundent</groupId>
                <artifactId>kotlin-xml-builder</artifactId>
                <version>1.9.0</version>
            </dependency>
            <dependency>
                <groupId>net.pwall.json</groupId>
                <artifactId>json-kotlin-schema</artifactId>
                <version>0.44</version>
            </dependency>
            <dependency>
                <groupId>org.apache.tika</groupId>
                <artifactId>tika-core</artifactId>
                <version>3.0.0</version>
            </dependency>

            <!-- Needed by postchain-client -->
            <dependency>
                <groupId>commons-io</groupId>
                <artifactId>commons-io</artifactId>
                <version>2.17.0</version>
            </dependency>

            <dependency>
                <groupId>org.mockito</groupId>
                <artifactId>mockito-core</artifactId>
                <version>5.7.0</version>
                <scope>test</scope>
            </dependency>
            <dependency>
                <groupId>org.mockito.kotlin</groupId>
                <artifactId>mockito-kotlin</artifactId>
                <version>5.2.1</version>
                <scope>test</scope>
            </dependency>
            <dependency>
                <groupId>org.mockito</groupId>
                <artifactId>mockito-inline</artifactId>
                <version>5.2.0</version>
                <scope>test</scope>
            </dependency>
            <dependency>
                <groupId>uk.org.webcompere</groupId>
                <artifactId>system-stubs-jupiter</artifactId>
                <version>2.1.6</version>
                <scope>test</scope>
            </dependency>

        </dependencies>
    </dependencyManagement>

    <dependencies>
        <dependency>
            <groupId>org.jetbrains.kotlin</groupId>
            <artifactId>kotlin-stdlib</artifactId>
        </dependency>
        <dependency>
            <groupId>org.jetbrains.kotlin</groupId>
            <artifactId>kotlin-test-junit5</artifactId>
            <scope>test</scope>
        </dependency>
        <dependency>
            <groupId>org.junit.jupiter</groupId>
            <artifactId>junit-jupiter</artifactId>
            <scope>test</scope>
        </dependency>
        <dependency>
            <groupId>com.willowtreeapps.assertk</groupId>
            <artifactId>assertk-jvm</artifactId>
            <version>0.26.1</version>
            <scope>test</scope>
        </dependency>
    </dependencies>

    <profiles>
        <profile>
            <id>ci</id>
            <build>
                <plugins>
                    <plugin>
                        <groupId>org.jetbrains.kotlin</groupId>
                        <artifactId>kotlin-maven-plugin</artifactId>
                        <configuration>
                            <args>
                                <arg>-Werror</arg>
                            </args>
                        </configuration>
                    </plugin>
                </plugins>
            </build>
        </profile>
        <profile>
            <id>docker-arm</id>
            <activation>
                <os>
                    <family>mac</family>
                    <arch>aarch64</arch>
                </os>
            </activation>
            <build>
                <pluginManagement>
                    <plugins>
                        <plugin>
                            <groupId>com.google.cloud.tools</groupId>
                            <artifactId>jib-maven-plugin</artifactId>
                            <executions>
                                <execution>
                                    <id>docker-build</id>
                                    <configuration>
                                        <from>
                                            <platforms>
                                                <platform>
                                                    <os>linux</os>
                                                    <architecture>arm64</architecture>
                                                </platform>
                                            </platforms>
                                        </from>
                                    </configuration>
                                </execution>
                            </executions>
                        </plugin>
                    </plugins>
                </pluginManagement>
            </build>
        </profile>
        <profile>
            <id>docker-push</id>
            <build>
                <pluginManagement>
                    <plugins>
                        <plugin>
                            <groupId>com.google.cloud.tools</groupId>
                            <artifactId>jib-maven-plugin</artifactId>
                            <executions>
                                <execution>
                                    <id>docker-push</id>
                                    <phase>deploy</phase>
                                    <goals>
                                        <goal>build</goal>
                                    </goals>
                                    <configuration>
                                        <from>
                                            <platforms>
                                                <platform>
                                                    <architecture>amd64</architecture>
                                                    <os>linux</os>
                                                </platform>
                                                <platform>
                                                    <architecture>arm64</architecture>
                                                    <os>linux</os>
                                                </platform>
                                            </platforms>
                                        </from>
                                        <to>
                                            <!--suppress UnresolvedMavenProperty -->
                                            <image>${gitlab.registry}/${image.name}</image>
                                            <tags>
                                                <tag>latest</tag>
                                                <tag>${project.version}</tag>
                                            </tags>
                                            <auth>
                                                <!--suppress UnresolvedMavenProperty -->
                                                <username>${env.CI_REGISTRY_USER}</username>
                                                <!--suppress UnresolvedMavenProperty -->
                                                <password>${env.CI_REGISTRY_PASSWORD}</password>
                                            </auth>
                                        </to>
                                    </configuration>
                                </execution>
                            </executions>
                        </plugin>
                    </plugins>
                </pluginManagement>
            </build>
        </profile>
        <profile>
            <id>coverage</id>
            <build>
                <plugins>
                    <plugin>
                        <groupId>org.jacoco</groupId>
                        <artifactId>jacoco-maven-plugin</artifactId>
                        <version>0.8.10</version>
                        <configuration>
                            <excludes>
                                <!-- Generated sources -->
                                <exclude>com/chromia/directory1/**</exclude>
                                <!-- Inner classes of ReplCommand (Dummy OutputCannelFactory -->
                                <exclude>com/chromia/cli/ReplCommand$*</exclude>
                                <!-- Copied from mordant -->
                                <exclude>com/chromia/cli/tools/mordant/*</exclude>
                            </excludes>
                        </configuration>
                        <executions>
                            <execution>
                                <id>default-prepare-agent</id>
                                <goals>
                                    <goal>prepare-agent</goal>
                                </goals>
                            </execution>
                            <execution>
                                <id>default-prepare-agent-integration</id>
                                <goals>
                                    <goal>prepare-agent-integration</goal>
                                </goals>
                            </execution>
                            <execution>
                                <id>default-report</id>
                                <phase>prepare-package</phase>
                                <goals>
                                    <goal>report</goal>
                                </goals>
                            </execution>
                            <execution>
                                <id>default-report-integration</id>
                                <phase>prepare-package</phase>
                                <goals>
                                    <goal>report-integration</goal>
                                </goals>
                            </execution>
                        </executions>
                    </plugin>
                </plugins>
            </build>
        </profile>

        <profile>
            <id>artifact</id>
            <activation>
                <activeByDefault>true</activeByDefault>
                <property>
                    <name>!local</name>
                </property>
            </activation>
            <build>
                <plugins>
                    <plugin>
                        <inherited>false</inherited>
                        <groupId>org.apache.maven.plugins</groupId>
                        <artifactId>maven-scm-plugin</artifactId>
                        <version>1.11.2</version>
                        <executions>
                            <execution>
                                <id>d1-resources</id>
                                <phase>generate-sources</phase>
                                <goals>
                                    <goal>checkout</goal>
                                </goals>
                                <configuration>
                                    <connectionUrl>scm:git:https://gitlab.com/chromaway/core/directory-chain.git
                                    </connectionUrl>
                                    <checkoutDirectory>${project.build.directory}/directory-chain
                                    </checkoutDirectory>
                                    <scmVersion>${directory.chain.version}</scmVersion>
                                    <scmVersionType>tag</scmVersionType>
                                    <skipCheckoutIfExists>true</skipCheckoutIfExists>
                                </configuration>
                            </execution>
                            <execution>
                                <id>library-chain-checkout</id>
                                <phase>generate-sources</phase>
                                <goals>
                                    <goal>checkout</goal>
                                </goals>
                                <configuration>
                                    <connectionUrl>scm:git:https://bitbucket.org/chromawallet/library-chain.git
                                    </connectionUrl>
                                    <checkoutDirectory>${project.build.directory}/library-chain
                                    </checkoutDirectory>
                                    <scmVersion>main</scmVersion>
                                    <scmVersionType>branch</scmVersionType>
                                    <skipCheckoutIfExists>true</skipCheckoutIfExists>
                                </configuration>
                            </execution>
                        </executions>
                    </plugin>
                </plugins>
            </build>
        </profile>
        <profile>
            <id>local</id>
            <activation>
                <property>
                    <name>local</name>
                </property>
            </activation>
            <properties>
                <directory.source>${project.basedir}/../../directory-chain/src</directory.source>
                <library-chain.source>${project.basedir}/../../library-chain/src</library-chain.source>
            </properties>
        </profile>
    </profiles>

</project>
